# Generated by Django 3.2.3 on 2021-05-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=6)),
            ],
        ),
    ]
