# Generated by Django 3.2.3 on 2021-05-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=30)),
                ('max_participants', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
