# Generated by Django 3.2.3 on 2021-05-23 05:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_register_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register_event',
            new_name='event_registration',
        ),
    ]
