# Generated by Django 3.2.3 on 2021-05-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_user_id'),
        ('events', '0003_rename_register_event_event_registration'),
    ]

    operations = [
    ]
